name: voicetype
channels:
  - conda-forge
dependencies:
  - python
  - fastapi>=0.93.0
  - loguru
  - pyaudio
  - pysoundfile
  - speechrecognition

  # settings
  - pydantic-settings
  - toml

  # using aider-chat only for litellm
  - aider-chat

  # needed by faster-whisper gpu
  - libcublas
  - cudnn

  # system tray
  - pystray
  - gtk3  # unsure if needed
  - gobject-introspection  # unsure if needed
  - pygobject

  # dev
  - ruff
  - pre-commit

  # pip
  - pip
  - pip:
    # pynput fork
    - pynput @ git+https://github.com/Adam-D-Lewis/pynput@26fe001ada956c0ad023ea0e3aa3c7dded3526ad

    # whisper
    - openai-whisper
    - faster-whisper

variables:
  VAR1: valueA
  VAR2: valueB
